name: Container
on: push

#jobs:
#    node-docker:
#        runs-on: ubuntu-latest
#        container:
#            image: node:14-alpine3.16
#        steps:
#            - name: Log node version
#              run: |
#                  node -v
#                  cat /etc/os-release

jobs:
    docker-steps:
        runs-on: ubuntu-latest
        container:
            image: node:18-bullseye
        steps:
            - name: log main node version
              run: node -v
            - name: Step with docker
              uses: docker://node:16-alpine3.16
              with:
                  entrypoint: /bin/echo
                  args: 'Hello World'
            - name: Log node version
              uses: docker://node:16-alpine3.16
              with:
                  entrypoint: /usr/local/bin/node
                  args: -v
            - uses: actions/checkout@v3
            - name: Run a script
              uses: docker://node:16-alpine3.16
              with:
                  entrypoint: ${GITHUB_REPOSITORY}/script.sh
                  args: "Some string"
    node-docker:
        runs-on: ubuntu-latest
        services:
            app:
                image: alialaa17/node-api
                ports:
                    - 3001:3000
            mongo:
                image: mongo
                ports:
                    - "27017:27017"
        steps:
            - name: Post a user
              run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json''
               -d ''{"username": "hello", "address": "gegetsfra"}'''
            - name: Get users
              run: curl http://localhost:3001/api/users