name: Shell Commands

on: [push]

jobs:
    run-shell-command:
        runs-on: linux-latest
        steps:
            - name: echo a string
              run: echo "Hello world"
            - name: multiline script
              run: |
                  node -v
                  npm -v
            - name: python command
              run: |
                  import platform
                  print (platform.processor())
              shell: python

